services:

  camera:
    build: .
    devices:
      - /dev/video0:/dev/video0
    command: >
      ros2 run v4l2_camera v4l2_camera_node
        --ros-args 
        -p video_device:=/dev/video0
        -p pixel_format:=YUYV
        -p output_encoding:=yuv422_yuy2
        -p image_size:="[640,480]" 
        -p camera_frame_id:=camera_optical_link

  rviz:
    image: husarion/rviz2:humble-11.2.6
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

  ffmpeg_compressor:
    image: husarion/ffmpeg-streamer:humble-1.0.0-20240329
    environment:
      - TYPE=ENCODER
      - RAW_TOPIC=/image_raw
      - FFMPEG_TOPIC=/image_raw/ffmpeg_best_effort

  ffmpeg_decompressor:
    image: husarion/ffmpeg-streamer:humble-1.0.0-20240329
    environment:
      - TYPE=DECODER
      - RAW_TOPIC=/image_raw/ffmpeg_decompressed
      - FFMPEG_TOPIC=/image_raw/ffmpeg_best_effort