---
/image_republisher:
  ros__parameters:
    # list encoders:
    #   $ ffmpeg -encoders
    # list available presets:
    #   $ ffmpeg -h encoder=hevc_nvenc
    ffmpeg_image_transport:
      encoding: hevc_nvenc
      preset: llhp
      tune: ll
